// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJZQmkqNJTyxO8BCl3ZcRRUElYJ56yoN0',
    appId: '1:181202602436:web:d133efedefa8d1a6a5fc91',
    messagingSenderId: '181202602436',
    projectId: 'route-gpt',
    authDomain: 'route-gpt.firebaseapp.com',
    storageBucket: 'route-gpt.firebasestorage.app',
    measurementId: 'G-WTR01JKE7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbIysg3NRhcB3bIeDP9LpddYLPUiy3Jso',
    appId: '1:181202602436:android:742a26e36ce4750aa5fc91',
    messagingSenderId: '181202602436',
    projectId: 'route-gpt',
    storageBucket: 'route-gpt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDJivPxLxUxia8NtHAqb5a6T6b3C-BnFs',
    appId: '1:181202602436:ios:25f8cf8bed329d55a5fc91',
    messagingSenderId: '181202602436',
    projectId: 'route-gpt',
    storageBucket: 'route-gpt.firebasestorage.app',
    iosBundleId: 'com.route.gpt',
  );
}
